export const Routes = {
    AUTH: {
        LOGIN: '/auth/login',
        SIGNUP: '/auth/signup',
        EMAIL_EXISTS: '/auth/email/exists',
        PHONE_EXISTS: '/auth/phone/exists',
        SEND_VERIFICATION_EMAIL: '/auth/email/send',
        VERIFY_EMAIL: '/auth/email/verify',
        FORGOT_PASSWORD: '/auth/password/forgot',
        UPDATE_PASSWORD: '/auth/user/password',
        USER_INFO: '/auth/user/info',
        UPDATE_USER: '/auth/user/update',
    },
    ASSET: {
        TRANSFER: '/asset/transfer',
        DETAILS: '/asset/details',
        DELETE: '/asset/delete',
        ASSETLIST: '/asset/assetlist',
        LEDGERLIST: '/asset/ledgerlist',
        LEDGER_DETAILS: '/asset/ledger/details',
        ASSET_STATS: '/asset/stats',
        BALANCES: '/asset/balances',
    },
    ASSET21: {
        ADDRESS: '/asset21/address',
        BALANCE: '/asset21/balance',
        CONFIG: '/asset21/config',
        CUSTOMERS: '/asset21/customers',
        DEPLOY: '/asset21/deploy',
        REGISTER: '/asset21/register',
        REQUEST: '/asset21/request',
        SYNC: '/asset21/sync',
        TRANSFER: '/asset21/transfer',
        UTXOS: '/asset21/utxos',
        OUTPOINT: '/asset21',
    },
    UTILITY: {
        REGISTER: '/utility/register',
        UPDATE: '/utility/update',
        MINT: '/utility/mint',
        REDEEM: '/utility/redeem',
    },
    DATA_INTEGRITY: {
        FILE_UPLOAD: '/data-integrity/file',
        TEXT_UPLOAD: '/data-integrity/text',
    },
    WALLET: {
        CREATE: '/wallet/create',
        UPDATE_DEFAULT: '/wallet/default',
        LIST: '/wallet/list',
        ADDRESS_CREATE: '/wallet/address/create',
        ADDRESS_LIST: '/wallet/addresses',
    },
    PAYMAIL: {
        CREATE: '/paymail/create',
        LIST: '/paymail/list',
        UPDATE_DEFAULT: '/paymail/default',
        DELETE: '/paymail/delete',
    },
    TEAM: {
        ACCEPT: '/team/accept',
        INVITES_LIST: '/team/invites',
        CREATE_INVITE: '/team/invites',
        PENDING_INVITES: '/team/invites/pending',
        LIST: '/team/list',
        MEMBERS_LIST: '/team/members',
        UPDATE_ROLE: '/team/members/role',
        REMOVE_MEMBER: '/team/remove',
    },
} as const;
