export const Routes = {
    AUTH: {
        LOGIN: '/auth/login',
        SIGNUP: '/auth/signup',
    },
    ASSET: {
        REGISTER: '/asset/register',
        UPDATE: '/asset/update',
        DETAILS: '/asset/details',
        MINT: '/asset/mint',
        TRANSFER: '/asset/transfer',
        MERGE: '/asset/merge',
        REDEEM: '/asset/redeem',
        DELETE: '/asset/delete',
        ASSETLIST: '/asset/assetlist',
        LEDGERLIST: '/asset/ledgerlist',
        LEDGER_DETAILS: '/asset/ledger/details',
        ASSET_STATS: '/asset/stats',
    },
    DATA_INTEGRITY: {
        FILE_UPLOAD: '/data-integrity/file/upload',
        TEXT_UPLOAD: '/data-integrity/text/upload',
    },
    WALLET: {
        CREATE: '/wallet/create',
        UPDATE_DEFAULT: '/wallet/default',
        LIST: '/wallet/list',
        ADDRESS_CREATE: '/wallet/address/create',
        ADDRESS_LIST: '/wallet/addresses',
    },
    PAYMAIL: {
        CREATE: '/paymail/create',
        LIST: '/paymail/list',
        UPDATE_DEFAULT: '/paymail/default',
        DELETE: '/paymail/delete',
    },
    PAY: {
        ADDRESS: '/pay/address',
        EMAIL: '/pay/email',
        PAYMAIL: '/pay/paymail',
    },
    TEAM: {
        ACCEPT: '/team/accept',
        INVITES_LIST: '/team/invites',
        CREATE_INVITE: '/team/invites',
        PENDING_INVITES: '/team/invites/pending',
        LIST: '/team/list',
        MEMBERS_LIST: '/team/members',
        UPDATE_ROLE: '/team/members/role',
        REMOVE_MEMBER: '/team/remove',
    },
} as const;
